<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Desk-67A" name="automation_Testcases.SignUp_Test" tests="9" failures="1" timestamp="24 Aug 2017 10:54:38 GMT" time="400.824" errors="0">
  <testcase name="SignUp_Successful_TC" time="47.740" classname="automation_Testcases.SignUp_Test"/>
  <testcase name="SignUp_Blank_FullName_TC" time="40.315" classname="automation_Testcases.SignUp_Test"/>
  <testcase name="SignUp_Blank_Email_TC" time="49.454" classname="automation_Testcases.SignUp_Test"/>
  <testcase name="SignUp_Blank_Password_TC" time="43.350" classname="automation_Testcases.SignUp_Test"/>
  <testcase name="SignUp_Invalid_EmailFormat_TC" time="57.180" classname="automation_Testcases.SignUp_Test"/>
  <testcase name="SignUp_Invalid_PasswordFormat_TC" time="30.934" classname="automation_Testcases.SignUp_Test"/>
  <testcase name="Registered_Email_TC" time="55.171" classname="automation_Testcases.SignUp_Test">
    <failure type="java.lang.AssertionError" message="Validation message for invalid credentials is incorrect expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Validation message for invalid credentials is incorrect expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at Common_Utility.Utils.verify_errorMsg(Utils.java:201)
	at automation_Testcases.SignUp_Test.Registered_Email_TC(SignUp_Test.java:242)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
    </failure>
  </testcase> <!-- Registered_Email_TC -->
  <testcase name="Popup_Privacy_Policy_TC" time="46.967" classname="automation_Testcases.SignUp_Test"/>
  <testcase name="Popup_T_and_C_TC" time="29.713" classname="automation_Testcases.SignUp_Test"/>
</testsuite> <!-- automation_Testcases.SignUp_Test -->
